"""Context writer — fetch CLARKE session context and write into workspace files.

This is the core bridge between CLARKE's dynamic context system and OpenClaw's
file-based prompt compilation. The Brain reads SOUL.md and AGENTS.md on every
LLM call, so writing CLARKE context into these files means every interaction
gets CLARKE-augmented context automatically.

User content outside the <!-- clarke:start/end --> markers is preserved.
"""

import sys
from datetime import UTC, datetime
from pathlib import Path

import httpx
import yaml

CLARKE_START_MARKER = "<!-- clarke:start -->"
CLARKE_END_MARKER = "<!-- clarke:end -->"


def fetch_session_context(
    endpoint: str,
    tenant_id: str,
    project_id: str,
    agent_slug: str,
) -> str:
    """Fetch rendered session context from CLARKE API."""
    resp = httpx.post(
        f"{endpoint}/agents/session-context",
        json={
            "tenant_id": tenant_id,
            "project_id": project_id,
            "agent_slug": agent_slug,
            "format": "markdown",
        },
        timeout=30.0,
    )
    resp.raise_for_status()
    return resp.text


def write_soul_md(workspace: Path, context_md: str, original_content: str | None = None) -> None:
    """Write SOUL.md with CLARKE context injected between markers.

    Content outside the markers is preserved. If no markers exist, they are
    appended at the end of the file.
    """
    soul_path = workspace / "SOUL.md"
    now = datetime.now(UTC).isoformat()

    clarke_block = f"""{CLARKE_START_MARKER}
<!-- Auto-generated by CLARKE. Do not edit between these markers. -->
<!-- Last refreshed: {now} -->

{context_md}

{CLARKE_END_MARKER}"""

    if original_content and CLARKE_START_MARKER in original_content:
        # Replace existing CLARKE block
        import re

        pattern = re.escape(CLARKE_START_MARKER) + r".*?" + re.escape(CLARKE_END_MARKER)
        new_content = re.sub(pattern, clarke_block, original_content, flags=re.DOTALL)
    elif original_content:
        # Append CLARKE block after existing content
        new_content = original_content.rstrip() + "\n\n" + clarke_block
    else:
        new_content = clarke_block

    soul_path.write_text(new_content + "\n")


def write_agents_md(
    workspace: Path,
    context_md: str,
    endpoint: str,
    tenant_id: str,
    project_id: str,
    agent_slug: str,
) -> None:
    """Write AGENTS.md with CLARKE connection frontmatter + context."""
    agents_path = workspace / "AGENTS.md"
    now = datetime.now(UTC).isoformat()

    content = f"""---
clarke_endpoint: {endpoint}
agent_slug: {agent_slug}
tenant_id: {tenant_id}
project_id: {project_id}
clarke_refreshed_at: {now}
---

{context_md}
"""
    agents_path.write_text(content)


def read_clarke_connection(workspace: Path) -> dict | None:
    """Read CLARKE connection info from AGENTS.md YAML frontmatter."""
    agents_path = workspace / "AGENTS.md"
    if not agents_path.exists():
        return None

    text = agents_path.read_text()
    if not text.startswith("---"):
        return None

    parts = text.split("---", 2)
    if len(parts) < 3:
        return None

    frontmatter = yaml.safe_load(parts[1])
    if not frontmatter or "clarke_endpoint" not in frontmatter:
        return None

    return frontmatter


def fetch_session_greeting(endpoint: str, tenant_id: str) -> str:
    """Build a concise CLARKE status greeting for session start.

    Returns a one-liner like:
      CLARKE is healthy | 2 agents, 8 skills, 1 policy | /clarke for dashboard
    """
    status = "offline"
    agents = 0
    policies = 0

    try:
        health_resp = httpx.get(f"{endpoint}/health", timeout=5.0)
        if health_resp.status_code == 200:
            data = health_resp.json()
            status = data.get("status", "unknown")
    except (httpx.ConnectError, httpx.TimeoutException):
        return "CLARKE is offline | start with: make dev"

    try:
        agents_resp = httpx.get(
            f"{endpoint}/agents/profiles",
            params={"tenant_id": tenant_id, "status": "active"},
            timeout=5.0,
        )
        if agents_resp.status_code == 200:
            agent_list = agents_resp.json()
            agents = len(agent_list)
    except (httpx.ConnectError, httpx.HTTPStatusError):
        pass

    try:
        policy_resp = httpx.get(
            f"{endpoint}/policy",
            params={"tenant_id": tenant_id},
            timeout=5.0,
        )
        if policy_resp.status_code == 200:
            policies = len(policy_resp.json())
    except (httpx.ConnectError, httpx.HTTPStatusError):
        pass

    parts = [f"CLARKE is {status}"]

    stats = []
    if agents:
        stats.append(f"{agents} agent{'s' if agents != 1 else ''}")
    if policies:
        stats.append(f"{policies} {'policies' if policies != 1 else 'policy'}")
    if stats:
        parts.append(" | ".join(stats))

    parts.append("/clarke for dashboard")

    return " | ".join(parts)


def refresh(workspace: Path | None = None) -> None:
    """Refresh SOUL.md and AGENTS.md from CLARKE and print a session greeting.

    Reads connection info from AGENTS.md frontmatter, fetches fresh context,
    rewrites both files, and outputs a greeting to stdout for the session start.
    """
    ws = workspace or Path.cwd()

    connection = read_clarke_connection(ws)
    if not connection:
        print("No CLARKE connection in AGENTS.md — skipping refresh", file=sys.stderr)
        return

    endpoint = connection["clarke_endpoint"]
    tenant_id = connection["tenant_id"]
    project_id = connection["project_id"]
    agent_slug = connection["agent_slug"]

    # Fetch and write context
    try:
        context_md = fetch_session_context(endpoint, tenant_id, project_id, agent_slug)
    except (httpx.ConnectError, httpx.HTTPStatusError) as e:
        print(f"CLARKE context refresh failed: {e}", file=sys.stderr)
        # Still output a greeting even if context fetch fails
        print(fetch_session_greeting(endpoint, tenant_id))
        return

    # Preserve existing SOUL.md content outside markers
    soul_path = ws / "SOUL.md"
    original_soul = soul_path.read_text() if soul_path.exists() else None

    write_soul_md(ws, context_md, original_soul)
    write_agents_md(ws, context_md, endpoint, tenant_id, project_id, agent_slug)

    # Output greeting to stdout for OpenClaw session start display
    greeting = fetch_session_greeting(endpoint, tenant_id)
    print(greeting)
